name: Pull Request

on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
         ruby-version: 2.6.10

      - name: Update RubyGems
        run: gem update --system 3.2.3

      - name: Install Bundler
        run: gem install bundler

      - name: Install gems
        run: bundle install

      - name: Swift Packages Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            Build/SourcePackages
            Build/Build/Products
          key: ${{ runner.os }}-deps-v1-${{ hashFiles('BILDsolid.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
          restore-keys: ${{ runner.os }}-deps-v1-

      - name: List Directory Contents
        run: ls -R
    
      - name: Build IPA
        run: |
          if [ -d "DemoCICD.xcodeproj" ]; then
            xcodebuild clean -project DemoCICD.xcodeproj
            xcodebuild archive -project DemoCICD.xcodeproj -scheme DemoCICD -sdk iphoneos -configuration AppStoreDistribution -archivePath $PWD/build/DemoCICD.xcarchive -configuration "Release" -destination generic/platform=iOS -allowProvisioningUpdates
            xcodebuild -exportArchive -archivePath $PWD/build/DemoCICD.xcarchive -exportOptionsPlist exportOptions.plist -exportPath $PWD/build/IPA
          else
            echo "Project not found. Listing directory contents:"
            ls -R
            exit 1
          fi
      
    
      - name: Upload IPA to Artifacts
        if: success()
        uses: actions/upload-artifact@v2
        with:
         name: DemoCICD-IPA
         path: build/IPA/*.ipa